# Generated by Django 4.2.3 on 2023-07-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher.', max_length=50)),
                ('website', models.URLField(help_text='The publishers website.')),
                ('email', models.EmailField(help_text='The publishers email.', max_length=254)),
            ],
        ),
    ]
